#
# Simple Completion Language Server
#
# https://github.com/estin/simple-completion-language-server
#
# Useful for scanning the current buffer for completions and for one off
# snippets.
#
[language-server.scls]
command = "simple-completion-language-server"

[language-server.scls.config]
max_completion_items = 20            # set max completion results len for each group: words, snippets, unicode-input
snippets_first = true                # completions will return before snippets by default
snippets_inline_by_word_tail = false # suggest snippets by WORD tail, for example text `xsq|` become `x^2|` when snippet `sq` has body `^2`
feature_words = true                 # enable completion by word
feature_snippets = true              # enable snippets
feature_unicode_input = true         # enable "unicode input"
feature_paths = true                 # enable path completion
feature_citations = false            # enable citation completion (only on `citation` feature enabled)

# write logs to /tmp/completion.log
[language-server.scls.environment]
RUST_LOG = "info,simple-completion-language-server=info"
LOG_FILE = "/tmp/completion.log"

[[language]]
name = "zig"
auto-format = false

[[language]]
name = "elixir"
auto-format = false

[[language]]
name = "python"
auto-format = false

[[language]]
name = "git-commit"
language-servers = ["scls"]
