#! /bin/sh

bspc config border_width          2
bspc config window_gap            3

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config top_padding           30
bspc config normal_border_color "#000000"
bspc config active_border_color "#333333"
bspc config focused_border_color "#ffb52a"

# LEFT
# DP-4 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 509mm x 286mm
bspc monitor DP-4 --reset-desktops I II III IV V

# CENTER
# DP-0 connected primary 1920x1200+1920+0 (normal left inverted right x axis y axis) 546mm x 352mm
bspc monitor DP-0 --reset-desktops VI VII VIII IX X

# RIGHT
# DP-2 connected 1920x1080+3840+0 (normal left inverted right x axis y axis) 509mm x 286mm
bspc monitor DP-2 --reset-desktops XI XII XIII XIV XV

# Floating rules
bspc rule -a hamster state=floating monitor=DP-0
