#!/bin/sh

# (re)load sxhkd
if hash sxhkd >/dev/null 2>&1; then
    sxhkd -c "$HOME/.config/bspwm/sxhkd/sxhkdrc" &
fi

# (re)load polybar
if hash polybar >/dev/null 2>&1; then
    case $(hostname) in
      chungus)
        polybar -c "$HOME/.config/bspwm/polybar/config.ini" left &
        polybar -c "$HOME/.config/bspwm/polybar/config.ini" center &
        polybar -c "$HOME/.config/bspwm/polybar/config.ini" right &
        ;;

      thinkboi)
        polybar -c "$HOME/.config/bspwm/polybar/config.ini" thinkboi &
        ;;
    esac
fi

read -r THEME < ~/.config/theme

export XDG_CURRENT_DESKTOP='bspwm'

# Make java stop trying to reparent shit when this is not
# a parenting WM
export _JAVA_AWT_WM_NONREPARENTING=1

bspc config border_width          5
bspc config window_gap            0

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
# bspc config focus_follows_pointer true
bspc config focus_follows_pointer false
bspc config top_padding           30
bspc config pointer_modifier      mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_corner
bspc config pointer_action3       resize_side

bspc config normal_border_color "#10b0fe"
bspc config presel_feedback_color "#ffa023"
bspc config active_border_color "#d2ecff"
bspc config focused_border_color "#ff637f"

# Monitors
for monitor in $(bspc query -M --names); do
    bspc monitor "$monitor" -d desktop-0 desktop-1 desktop-2 desktop-3 desktop-4 desktop-5
done

# RULES
bspc rule -a Zoom state=floating center=on focus=off
bspc rule -a zoom state=floating center=on focus=off
bspc rule -a ksnip state=floating center=on
bspc rule -a SpeedCrunch state=floating
bspc rule -a copyq state=floating

# Background Color
hsetroot -solid "#373a41"
