#!/bin/sh

# (re)load sxhkd
if hash sxhkd >/dev/null 2>&1; then
    sxhkd -c "$HOME/.config/bspwm/sxhkd/sxhkdrc" &
fi

# (re)load polybar
if hash polybar >/dev/null 2>&1; then
    polybar -c "$HOME/.config/bspwm/polybar/config.ini" left &
    polybar -c "$HOME/.config/bspwm/polybar/config.ini" center &
    polybar -c "$HOME/.config/bspwm/polybar/config.ini" right &
fi

# Make java stop trying to reparent shit when this is not
# a parenting WM
export _JAVA_AWT_WM_NONREPARENTING=1

bspc config border_width          2
bspc config window_gap            3

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
# bspc config focus_follows_pointer true
bspc config focus_follows_pointer false
bspc config top_padding           30
bspc config pointer_modifier      mod4
bspc config pointer_action1       move
bspc config pointer_action2       resize_corner
bspc config pointer_action3       resize_side

bspc config normal_border_color "#44475a"
#bspc config active_border_color "#bd93f9"
#bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"

# LEFT MONITOR
bspc monitor DisplayPort-0 --reset-desktops desktop-0 desktop-1 desktop-2 desktop-3 desktop-4 desktop-5

# CENTER MONITOR
bspc monitor DisplayPort-1 --reset-desktops desktop-0 desktop-1 desktop-2 desktop-3 desktop-4 desktop-5

# RIGHT MONITOR
bspc monitor DisplayPort-2 --reset-desktops desktop-0 desktop-1 desktop-2 desktop-3 desktop-4 desktop-5

# RULES
bspc rule -a Zoom state=floating center=on
bspc rule -a zoom state=floating center=on
bspc rule -a ksnip state=floating center=on
bspc rule -a SpeedCrunch state=floating
bspc rule -a copyq state=floating
